services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jXd1Pi3hsiSotm9BHKgw6X0yfN
      - POSTGRES_DB=reddit
  redis:
    image: "redis"
    ports:
      - "6379:6379"
