services:
  postgres:
    image: "postgres"
    networks:
      - shared-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddit
  redis:
    image: "redis"
    networks:
      - shared-network
    ports:
      - "6379:6379"
  cloudtech-2-api:
    image: "cloudtech-2-api"
    depends_on:
      - postgres
      - redis
    networks:
      - shared-network
    ports:
      - "9000:8000"
  cloudtech-2-cache:
    image: "cloudtech-2-cache"
    depends_on:
      - postgres
      - redis
    networks:
      - shared-network
    ports:
      - "9001:8000"
  
  cloudtech-2-frontend-1:
    image: "cloudtech-2-frontend"
    networks:
      - shared-network

  cloudtech-2-frontend-2:
    image: "cloudtech-2-frontend"
    networks:
      - shared-network

  cloudtech-2-frontend-3:
    image: "cloudtech-2-frontend"
    networks:
      - shared-network
  
  nginx:
    image: cloudtech-2-nginx
    ports:
      - "80:80"
    networks:
      - shared-network
    depends_on:
      - cloudtech-2-frontend-1
      - cloudtech-2-frontend-2
      - cloudtech-2-frontend-3

networks:
  shared-network:
