"""Changed post text attribute

Revision ID: fa036434a494
Revises: 6f8e91623e10
Create Date: 2024-05-21 17:16:39.337278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa036434a494'
down_revision: Union[str, None] = '6f8e91623e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
